Repository DDWU-UMC/FE, pull requests merged in 2025-02, with the labels that each got.

#7 [Feat] 이전 기수 프로젝트 관련 페이지 UI 구현
  src/App.jsx
  src/components/project/ProjectCard.jsx
  src/components/project/ProjectList.jsx
  src/components/project/ProjectPreviewCard.jsx
  src/components/project/ProjectPreviewCard2.jsx
  src/data/projectData.js
  src/pages/ProjectDetailPage.jsx
  src/pages/ProjectPage.jsx
Labels: ✨ Feature

#15 [Refactor] 운영진 페이지 디자인 변경, 헤더 현재 위치 추가
  src/components/header/MainHeader.jsx
  src/pages/ManagementPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#18 [Refactor] 프로젝트 리스트 페이지 디자인 적용
  src/components/project/ProjectCard.jsx
  src/components/project/ProjectList.jsx
  src/components/project/ProjectPreviewCard.jsx
  src/components/project/ProjectPreviewCard2.jsx
  src/database/projectData.js
  src/pages/ProjectPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#26 [Refactor] FAQ 디자인 적용 및 리팩토링
  src/components/FAQ/FAQItem.jsx
  src/components/FAQ/FAQList.jsx
  src/database/fqaData.json
  src/pages/FAQPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#29 refactor: 커리큘럼 디자인 수정
  src/database/curriculumData.json
  src/pages/CurriculumPage.jsx
  src/pages/MainPage.jsx
  src/pages/ManagementPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#31 [Feature] footer 구현, 서브 타이틀 배경 이미지 추가, 운영진 페이지 display: flex->glid 수정
  src/assets/instargram.svg
  src/assets/kakao.svg
  src/assets/mail.svg
  src/assets/underheaderImg.svg
  src/components/footer/MainFooter.jsx
  src/pages/CurriculumPage.jsx
  src/pages/MainPage.jsx
  src/pages/ManagementPage.jsx
Labels: ✨ Feature, 🔨 Refactor

#33 [Refactor] 프로젝트 관련 페이지 리팩토링
  src/App.jsx
  src/components/project/ProjectCard.jsx
  src/components/project/ProjectList.jsx
  src/components/project/ProjectPreviewCard.jsx
  src/components/project/ProjectPreviewCard2.jsx
  src/database/projectData.js
  src/database/projectData.json
  src/pages/ProjectDetailPage.jsx
  src/pages/ProjectPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#34 refactor: 메인 페이지 반응형 적용
  src/App.jsx
  src/assets/background-mobile.svg
  src/pages/CurriculumPage.jsx
  src/pages/FAQPage.jsx
  src/pages/MainPage.jsx
  src/pages/ManagementPage.jsx
  src/pages/ProjectDetailPage.jsx
  src/pages/ProjectPage.jsx
Labels: ✨ Feature, 🔨 Refactor

#43 [Refactor] 메인 별자리 이미지 추가
  src/assets/Pmday.jpg
  src/pages/MainPage.jsx
  src/pages/ProjectDetailPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#45 [Refactor] Footer 리팩토링
  src/App.css
  src/App.jsx
  src/components/footer/MainFooter.jsx
  src/pages/ProjectDetailPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#47 [Refactor] 프로젝트 디자인 수정 및 코드 리팩
  src/components/project/ProjectCard.jsx
  src/components/project/ProjectList.jsx
  src/pages/ProjectDetailPage.jsx
  src/pages/ProjectPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#53 [Refactor] 전체 리팩토링
  src/components/FAQ/FAQList.jsx
  src/pages/FAQPage.jsx
  src/pages/ProjectDetailPage.jsx
  src/pages/ProjectPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#56 [Deploy] dev -> main
  src/App.jsx
  src/assets/Pmday.jpg
  src/assets/info.svg
  src/assets/study.jpg
  src/components/FAQ/FAQList.jsx
  src/components/footer/MainFooter.jsx
  src/components/header/MainHeader.jsx
  src/components/project/ProjectCard.jsx
  src/components/project/ProjectList.jsx
  src/components/project/ProjectPreviewCard.jsx
  src/database/fqaData.json
  src/pages/CurriculumPage.jsx
  src/pages/FAQPage.jsx
  src/pages/MainPage.jsx
  src/pages/ManagementPage.jsx
  src/pages/ProjectDetailPage.jsx
  src/pages/ProjectPage.jsx
Labels: 🌏 Deploy

#85 [Refactor] 모바일 메인 디자인 수정
  src/main.jsx
  src/pages/MainPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#86 [Deploy] dev -> main
  src/main.jsx
  src/pages/MainPage.jsx
Labels: 🌏 Deploy

#98 [Refactor] 프로젝트 코드 리팩토링
  package-lock.json
  package.json
  src/components/project/ProjectCard.jsx
  src/components/project/ProjectList.jsx
  src/components/project/ProjectPreviewCard.jsx
  src/database/projectData.json
  src/pages/ProjectDetailPage.jsx
  src/pages/ProjectPage.jsx
Labels: 🔨 Refactor, 🎨 Html&css

#100 [Design] 메인 화면 포인터 추가
  src/pages/MainPage.jsx
Labels: 🎨 Html&css

#101 [Deploy] dev -> main
  package-lock.json
  package.json
  src/components/project/ProjectCard.jsx
  src/components/project/ProjectList.jsx
  src/components/project/ProjectPreviewCard.jsx
  src/database/projectData.json
  src/pages/MainPage.jsx
  src/pages/ProjectDetailPage.jsx
  src/pages/ProjectPage.jsx
Labels: 🌏 Deploy
